version: 2.1

workflows:
  pull-request-workflow:
    jobs:
      - pull-request-check:
          filters:
            branches:
              ignore:
                - main
                - ^0\.\d+

  main-branch-workflow:
    jobs:
      - main-branch-check:
          filters:
            branches:
              only:
                - main
                - ^0\.\d+

jobs:
  pull-request-check:
    docker:
      - image: vsaglib/vsag:ci-x86
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          keys:
            - fork-cache-{{ checksum "CMakeLists.txt" }}-{{ checksum ".circleci/fresh_ci_cache.commit" }}
      - run:
          command: export CMAKE_GENERATOR="Ninja" && make test_parallel
          no_output_timeout: 50m
      - save_cache:
          key: fork-cache-{{ checksum "CMakeLists.txt" }}-{{ checksum ".circleci/fresh_ci_cache.commit" }}
          paths:
            - ./build

  main-branch-check:
    docker:
      - image: vsaglib/vsag:ci-x86
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          keys:
            - main-ccache-{{ checksum "CMakeLists.txt" }}-{{ checksum ".circleci/fresh_ci_cache.commit" }}
      - run:
          command: export CMAKE_GENERATOR="Ninja" && make test_parallel
          no_output_timeout: 50m
      - save_cache:
          key: main-ccache-{{ checksum "CMakeLists.txt" }}-{{ checksum ".circleci/fresh_ci_cache.commit" }}
          paths:
            - ./build
